###################
### MY PROGRAMS ###
###################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$menu = pkill rofi || rofi -show drun
$browser = librewolf
$browser2 = flatpak run net.mullvad.MullvadBrowser
$waybar-restart = ~/.config/hypr/scripts/waybar-restart.sh
# $browser-out-mullvad = mullvad-exclude brave
