##############################
### WINDOWS AND WORKSPACES ###
##############################



# See https://wiki.hypr.land/Configuring/Window-Rules/ for more
# See https://wiki.hypr.land/Configuring/Workspace-Rules/ for workspace rules

# Example windowrules that are useful

windowrule {
    # Ignore maximize requests from all apps. You'll probably like this.
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    # Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

# Hyprland-run windowrule
windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

#Window rules criadas
windowrule {
  name = thunar
  match:class = Thunar
  float = on
  size = 970 630
  center = on
}

windowrule {
  name = open_file
  match:class = ^(xdg-desktop-portal-gtk|soffice|codium|electron)
  match:title = ^(Open File|Open Folder|Open|Save|Save As|Export|Import|Choose File|Rename|Open Workspace from File|Open folder as vault)
  float = on
  size = 970 630
  center = on
}

windowrule {
  name = discord_rules
  match:class = discord
  monitor = DP-1 silent
  workspace = 4 silent
}

windowrule {
  name = mullvad-vpn
  match:class = ^(Mullvad VPN)$
  float = on
  move = (monitor_w-window_w-20) 50
}

#Layer Rules Criadas
layerrule {
  name = rofi_rule
  match:namespace = rofi
  animation = popin 85%
  blur = on
}

layerrule {
  name = waybar_rule
  match:namespace = waybar
  no_anim = on
}

##########
###STEAM##
##########

windowrule {
  name = steam_sign_in
  match:class = steam
  match:title = Sign in to Steam
  center = on
}

windowrule {
  name = Games
  match:class = ^(steam_app_[0-9]+|gamescope)$
  immediate = on
  monitor= DP-2 silent
  workspace = 3 silent
  center = on
  content = game
  stay_focused = on
}

